version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        container_name: laravel_redis
        networks:
            - laravel_network

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_worker
        restart: always
        working_dir: /var/www/html
        command: php artisan queue:work
        environment:
            LOG_CHANNEL: "single"
        volumes:
            - .:/var/www/html
        networks:
            - laravel_network
networks:
    laravel_network:
        driver: bridge
